from serpy import Serializer, IntField, StrField, BoolField, Field
from taxonomy.serializers import *
from geography.serializers import *

class PersonSerializer(Serializer):
    id = IntField()
    first_name = StrField()
    middle_initial = StrField()
    last_name = StrField()
    suffix = StrField()

class SpecimenRecordImageSerializer(Serializer):
    id = IntField()
    get_image_url = Field(call=True)
    position = StrField()
    date = StrField()

class SpecimenRecordSerializer(Serializer):
    id = IntField()
    usi = StrField()
    images = SpecimenRecordImageSerializer(many=True, attr="specimen_images.all", call=True, required=False)
    # order_json = Field(required=False, call=False)
    # family_json = Field(required=False, call=False)
    # subfamily_json = Field(required=False, call=False)
    # tribe_json = Field(required=False, call=False)
    # genus_json = Field(required=False, call=False)
    # species_json = Field(required=False, call=False)
    # subspecies_json = Field(required=False, call=False)
    order = OrderSerializer(required=False)
    family = FamilySerializer(required=False)
    subfamily = SubfamilySerializer(required=False)
    tribe = TribeSerializer(required=False)
    genus = GenusSerializer(required=False)
    species = SpeciesSerializer(required=False)
    subspecies = SubspeciesSerializer(required=False)

    taxon_json = Field(call=False)
    display_determiner = Field(call=True)
    determined_year = IntField(required=False)
    sex = StrField()
    stage = StrField()
    display_preparer = Field(call=True)
    preparation = StrField()
    preparation_date = StrField(required=False)
    labels_printed = BoolField()
    labeled = BoolField()
    photographed = BoolField()
    identified = BoolField()
    collecting_trip = CollectingTripSerializer(required=False)
    country = CountrySerializer(required=False)
    state = StateSerializer(required=False)
    county = CountySerializer(required=False)
    locality = LocalitySerializer(required=False)
    gps = GPSSerializer(required=False)
    collected_date = StrField(required=False)
    full_date = StrField(required=False)
    num_date = StrField(required=False)
    display_collectors = Field(call=True)
    collector = PersonSerializer(many=True, attr="collector.all", call=True, required=False)
    method = StrField(required=False)
    weather = StrField(required=False)
    temp_F = StrField(required=False)
    temp_C = StrField(required=False)
    time_of_day = StrField(required=False)
    habitat = StrField(required=False)
    notes = StrField(required=False)