# Generated by Django 3.2.6 on 2021-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text="Enter the person's last name", max_length=50),
        ),
    ]
