# Generated by Django 3.2.6 on 2021-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0003_specimenrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenrecord',
            name='collector',
            field=models.ManyToManyField(help_text="Select the specimen's collector(s)", related_name='specimen_collectors', to='specimens.Person', verbose_name='Collector(s)'),
        ),
    ]
