# Generated by Django 3.2.6 on 2021-08-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0005_alter_specimenrecord_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.CharField(choices=[('dorsal', 'dorsal'), ('ventral', 'ventral'), ('lateral', 'lateral')], default='dorsal', help_text='Select the view of the specimen in the image', max_length=10)),
                ('date', models.DateField(help_text='Enter the date the image was taken')),
                ('usi', models.ForeignKey(help_text='Select the specimen in the image', on_delete=django.db.models.deletion.CASCADE, to='specimens.specimenrecord')),
            ],
        ),
    ]
