# Generated by Django 3.2.6 on 2021-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0007_alter_specimenrecordimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_initial',
            field=models.CharField(blank=True, help_text="Enter the person's middle initial", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, help_text='Enter a suffix, if the person has one', max_length=5, null=True),
        ),
    ]
