# Generated by Django 3.2.6 on 2021-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0008_auto_20210821_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='identified',
            field=models.BooleanField(help_text='Is the specimen identified to at least species?', null=True),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='labeled',
            field=models.BooleanField(help_text='Is the specimen labeled?', null=True),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='labels_printed',
            field=models.BooleanField(help_text='Are labels printed for the specimen?', null=True),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='photographed',
            field=models.BooleanField(help_text='Is the specimen photographed?', null=True),
        ),
    ]
