# Generated by Django 3.2.6 on 2021-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0009_auto_20210821_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='preparation',
            field=models.CharField(choices=[('spread', 'spread'), ('pinned', 'pinned'), ('minuten', 'minuten'), ('pointed', 'pointed'), ('envelope.', 'envelope'), ('container', 'container'), ('alcohol', 'alcohol')], default='spread', help_text="Select the specimen's preparation type", max_length=15, null=True),
        ),
    ]
