# Generated by Django 3.2.6 on 2021-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0010_alter_specimenrecord_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='determined_year',
            field=models.IntegerField(help_text='Enter the year the determination was made', null=True),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='unknown', help_text="Select the specimen's sex", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='stage',
            field=models.CharField(choices=[('egg', 'egg'), ('larva', 'larva'), ('nymph', 'nymph'), ('pupa', 'pupa'), ('adult', 'adult')], default='adult', help_text="Select the specimen's stage", max_length=10, null=True),
        ),
    ]
