# Generated by Django 3.2.6 on 2021-08-22 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0011_auto_20210821_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='determiner',
            field=models.ForeignKey(help_text='Select the person who determined the specimen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_determiners', to='specimens.person'),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='preparer',
            field=models.ForeignKey(help_text='Select the person who prepared the specimen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_preparers', to='specimens.person'),
        ),
    ]
