# Generated by Django 3.2.6 on 2021-08-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0012_auto_20210821_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='method',
            field=models.CharField(blank=True, help_text='Select the method used to collected the specimen', max_length=50, null=True),
        ),
    ]
