# Generated by Django 3.2.6 on 2021-08-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0013_alter_specimenrecord_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecordimage',
            name='usi',
            field=models.ForeignKey(help_text='Select the specimen in the image', on_delete=django.db.models.deletion.CASCADE, related_name='specimen_images', to='specimens.specimenrecord'),
        ),
    ]
