# Generated by Django 3.2.6 on 2022-01-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0019_alter_specimenrecord_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_initial',
            field=models.CharField(blank=True, default='', help_text="Enter the person's middle initial", max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text='Enter a suffix, if the person has one', max_length=5),
        ),
    ]
