# Generated by Django 3.2.6 on 2022-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0020_auto_20220117_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenrecord',
            name='temp_C',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='specimenrecord',
            name='temp_F',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
