# Generated by Django 3.2.6 on 2022-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0021_auto_20220123_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='temp_C',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='specimenrecord',
            name='temp_F',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
