# Generated by Django 3.2.6 on 2022-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0022_auto_20220123_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenrecord',
            name='collected_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='specimenrecord',
            name='full_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='specimenrecord',
            name='num_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
