# Generated by Django 3.2.6 on 2022-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0023_auto_20220207_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenrecord',
            name='subspecies_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
