# Generated by Django 3.2.6 on 2022-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0024_specimenrecord_subspecies_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenrecord',
            name='subspecies_json',
            field=models.JSONField(default=dict),
        ),
    ]
