# Generated by Django 3.2.6 on 2022-03-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0026_alter_specimenrecord_subspecies_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimenrecord',
            name='subspecies_value',
        ),
    ]
