# Generated by Django 3.2.6 on 2022-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0030_alter_specimenrecord_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='stage',
            field=models.CharField(choices=[('egg', 'egg'), ('larva', 'larva'), ('nymph', 'nymph'), ('pupa', 'pupa'), ('adult', 'adult')], default='adult', help_text="Select the specimen's stage", max_length=10),
        ),
    ]
