# Generated by Django 3.2.6 on 2022-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0031_alter_specimenrecord_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='preparation',
            field=models.CharField(choices=[('spread', 'spread'), ('pinned', 'pinned'), ('minuten', 'minuten'), ('pointed', 'pointed'), ('envelope', 'envelope'), ('container', 'container'), ('alcohol', 'alcohol')], default='spread', help_text="Select the specimen's preparation type", max_length=15),
        ),
    ]
