# Generated by Django 3.2.6 on 2022-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0032_alter_specimenrecord_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='', help_text='Select the month the specimen was collected, if known', max_length=10),
        ),
    ]
