# Generated by Django 3.2.6 on 2022-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0035_alter_specimenrecord_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='time_of_day',
            field=models.CharField(blank=True, default='', help_text="Enter the approximate time of the specimen's collection", max_length=50),
        ),
    ]
