# Generated by Django 3.2.6 on 2022-04-20 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0037_alter_specimenrecord_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Enter any other notes about the specimen'),
        ),
    ]
