# Generated by Django 3.2.6 on 2021-08-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(help_text='Select the order to which this family belongs', on_delete=django.db.models.deletion.CASCADE, related_name='families', to='taxonomy.order'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='tribe',
            field=models.ForeignKey(help_text='Select the tribe to which this genus belongs', on_delete=django.db.models.deletion.CASCADE, related_name='genera', to='taxonomy.tribe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(help_text='Select the genus to which this species belongs', on_delete=django.db.models.deletion.CASCADE, related_name='species', to='taxonomy.genus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='mona',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the MONA (Hodges) # for the species (Lepidoptera only)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='family',
            field=models.ForeignKey(help_text='Select the family to which this subfamily belongs', on_delete=django.db.models.deletion.CASCADE, related_name='subfamilies', to='taxonomy.family'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='species',
            field=models.ForeignKey(help_text='Select the species to which this subspecies belongs', on_delete=django.db.models.deletion.CASCADE, related_name='subspecies', to='taxonomy.species'),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='common_name',
            field=models.CharField(blank=True, help_text='Enter the common name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='subfamily',
            field=models.ForeignKey(help_text='Select the subfamily to which this tribe belongs', on_delete=django.db.models.deletion.CASCADE, related_name='tribes', to='taxonomy.subfamily'),
        ),
    ]
