# Generated by Django 3.2.6 on 2021-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_auto_20210821_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
