# Generated by Django 3.2.6 on 2021-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_family_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='alt_text',
            field=models.TextField(blank=True, default='', help_text='Enter alternative text for the image'),
        ),
    ]
