# Generated by Django 3.2.6 on 2021-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_family_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
