# Generated by Django 3.2.6 on 2022-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_alter_family_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='genus',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Enter the common name', max_length=100),
        ),
    ]
