# Generated by Django 4.0.4 on 2022-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_auto_20220319_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.FileField(blank=True, upload_to='insect-photos'),
        ),
    ]
