# Generated by Django 3.2.6 on 2021-08-18 14:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_auto_20210807_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('citation', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy', ckeditor.fields.RichTextField(blank=True, help_text='Enter taxonomy details', null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Enter species description', null=True)),
                ('distribution', ckeditor.fields.RichTextField(blank=True, help_text='Enter distribution details', null=True)),
                ('seasonality', ckeditor.fields.RichTextField(blank=True, help_text='Enter seasonality details', null=True)),
                ('habitat', ckeditor.fields.RichTextField(blank=True, help_text="Enter the species' habitat", null=True)),
                ('food', ckeditor.fields.RichTextField(blank=True, help_text='Enter info larval and adult food sources', null=True)),
                ('life_cycle', ckeditor.fields.RichTextField(blank=True, help_text='Enter details about the life cycle', null=True)),
                ('references', models.ManyToManyField(help_text='Enter citations used to write the info in the preciding fields', related_name='species_pages', to='pages.Reference')),
                ('species', models.OneToOneField(help_text='Select the species for this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_page', to='taxonomy.species')),
            ],
            options={
                'ordering': ['species'],
            },
        ),
    ]
