# Generated by Django 3.2.6 on 2021-09-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_speciespage_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciespage',
            name='title',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
