# Generated by Django 3.2.6 on 2021-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_speciespage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciespage',
            name='title',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
    ]
