# Generated by Django 3.2.6 on 2022-04-20 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_speciespage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciespage',
            name='taxonomy',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Enter taxonomy details'),
        ),
    ]
