# Generated by Django 3.2.6 on 2022-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_speciespage_life_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciespage',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='Enter citations used to write the info in the presiding fields', related_name='species_pages', to='pages.Reference'),
        ),
    ]
