# Generated by Django 3.2.6 on 2021-08-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20210809_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingtrip',
            name='states',
            field=models.ManyToManyField(related_name='collecting_trips', to='geography.State'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='county',
            field=models.ForeignKey(blank=True, help_text="Select the locality's county", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='geography.county'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(blank=True, help_text="Select the locality's state", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='geography.state'),
        ),
    ]
