# Generated by Django 3.2.6 on 2021-08-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0003_auto_20210809_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='country',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='county',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='state',
        ),
        migrations.AddField(
            model_name='locality',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='locality',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gps',
            name='locality',
            field=models.ForeignKey(help_text='Select the locality for this set of coordinates', on_delete=django.db.models.deletion.CASCADE, related_name='places_collected', to='geography.locality'),
        ),
    ]
