# Generated by Django 3.2.6 on 2021-08-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0004_auto_20210811_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='content_type',
            field=models.ForeignKey(default='', limit_choices_to={'model__in': ('country', 'state', 'county')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
