# Generated by Django 3.2.6 on 2021-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_alter_locality_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, help_text="Enter the locality's name", max_length=100),
        ),
    ]
