# Generated by Django 3.2.6 on 2021-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_alter_locality_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, help_text="Enter the locality's name", max_length=100, null=True),
        ),
    ]
