# Generated by Django 3.2.6 on 2021-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_alter_locality_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='range',
            field=models.CharField(blank=True, help_text='Enter the distance and direction of this locality from the nearest town', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='town',
            field=models.CharField(blank=True, help_text='Enter the nearest town', max_length=50, null=True),
        ),
    ]
