# Generated by Django 3.2.6 on 2021-08-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0008_auto_20210820_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Enter the latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Enter the longitude', max_digits=11, null=True),
        ),
    ]
