# Generated by Django 3.2.6 on 2021-08-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0009_auto_20210821_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='elevation',
            field=models.CharField(help_text='Enter the elevation in meters', max_length=15),
        ),
    ]
