# Generated by Django 3.2.6 on 2021-08-24 15:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_alter_collectingtrip_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingtrip',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
