# Generated by Django 3.2.6 on 2021-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0012_alter_collectingtrip_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingtrip',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
