# Generated by Django 3.2.6 on 2021-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0013_collectingtrip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectingtrip',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
