# Generated by Django 3.2.6 on 2022-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0014_alter_collectingtrip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_abbr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
