# Generated by Django 3.2.6 on 2022-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0015_county_county_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Enter the locality's name", max_length=100),
        ),
    ]
