# Generated by Django 3.2.6 on 2022-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0016_alter_locality_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='range',
            field=models.CharField(blank=True, default='', help_text='Enter the distance and direction of this locality from the nearest town', max_length=10),
        ),
    ]
