# Generated by Django 3.2.6 on 2021-09-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0012_alter_collectingtrip_notes'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insectimage',
            name='collecting_trip',
            field=models.ForeignKey(blank=True, help_text='Select the collecting trip during which the image was taken', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insect_images', to='geography.collectingtrip'),
        ),
    ]
