# Generated by Django 3.2.6 on 2021-09-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_insectimage_collecting_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitatimage',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='insectimage',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='plantimage',
            old_name='datetime',
            new_name='date',
        ),
    ]
